name: Trigger on registry_package

on: [ registry_package ]

jobs:
  test-if:
    runs-on: ubuntu-latest
    steps:
#      - run: echo ${{ toJSON(github.event.registry_package) }}
      - run: echo ${{ toJSON(github.event.registry_package.package_version.manifest) }}
