name: Trigger on registry_package

on: [ registry_package ]

jobs:
  test-if:
    runs-on: ubuntu-latest
    if: github.event.registry_package.package_type == 'npm' && fromJSON(github.event.registry_package.package_version.npm_metadata).scripts.image != null
    steps:
#      - run: echo ${{ toJSON(github.event.registry_package) }}
#      - run: echo ${{ fromJSON(github.event.registry_package.package_version.npm_metadata) }}
       - run: echo Done
